package Pokemon;

public enum Itens {
	// --- A - B ---
    ABSORB_BULB, ADAMANT_ORB, ANTIDOTE, ASSAULT_VEST, AWAKENING, 
    BERRY_JUICE, BINDING_BAND, BLACK_BELT, BLACK_GLASSES, BLACK_SLUDGE, 
    BRIGHT_POWDER, BURN_HEAL,
    
    // --- C ---
    CALCIUM, CARBOS, CELL_BATTERY, CHARCOAL, CHERI_BERRY, CHESTO_BERRY, 
    CHOICE_BAND, CHOICE_SCARF, CHOICE_SPECS, CLEANSING_TAG, COMET_SHARD, 
    COVERT_CLOAK,
    
    // --- D - F ---
    DAMP_ROCK, DAWN_STONE, DESTINY_KNOT, DIVE_BALL, DRAGON_FANG, DUSK_BALL, 
    DUSK_STONE, EJECT_BUTTON, EJECT_PACK, ELIXIR, ENERGY_ROOT, ETHER, 
    EVERSTONE, EXP_SHARE, EXPERT_BELT, FAST_BALL, FIRE_STONE, FLOAT_STONE, 
    FOCUS_BAND, FOCUS_SASH, FRESH_WATER, FULL_HEAL, FULL_RESTORE,
    
    // --- G - I ---
    GRASS_KNOT, GREAT_BALL, GRIP_CLAW, HARD_STONE, HEAL_BALL, HEART_SCALE, 
    HEAVY_BALL, HP_UP, HYPER_POTION, ICE_HEAL, ICY_ROCK, IRON, IRON_BALL,
    
    // --- L - M ---
    LEAF_STONE, LEFTOVERS, LEMONADE, LIFE_ORB, LIGHT_BALL, LIGHT_CLAY, 
    LUM_BERRY, LUXURY_BALL, MACHO_BRACE, MASTER_BALL, MAX_ELIXIR, MAX_ETHER, 
    MAX_POTION, MAX_REPEL, MAX_REVIVE, MENTAL_HERB, METAL_COAT, MIRACLE_SEED, 
    MOON_STONE, MOOMOO_MILK, MUSCLE_BAND, MYSTIC_WATER,
    
    // --- N - P ---
    NEST_BALL, NET_BALL, NEVER_MELT_ICE, NUGGET, ORAN_BERRY, PARALYZE_HEAL, 
    PEARL, PECHA_BERRY, POISON_BARB, POKE_BALL, POKE_DOLL, POTION, POWER_HERB, 
    PREMIER_BALL, PROTECTIVE_PADS, PROTEIN,
    
    // --- Q - S ---
    QUICK_BALL, QUICK_CLAW, RARE_CANDY, RAWST_BERRY, RAZOR_CLAW, RAZOR_FANG, 
    REAPER_CLOTH, RED_CARD, REPEL, REVIVE, ROCKY_HELMET, ROOM_SERVICE, 
    SAFARI_BALL, SCOPE_LENS, SHARP_BEAK, SHED_SHELL, SHINY_STONE, SILK_SCARF, 
    SILVER_POWDER, SITRUS_BERRY, SMOKE_BALL, SOFT_SAND, SOOTHE_BELL, SPELL_TAG, 
    STAR_PIECE, STARDUST, SUN_STONE, SUPER_POTION, SUPER_REPEL,
    
    // --- T - Z ---
    TERRAIN_EXTENDER, THUNDER_STONE, TIMER_BALL, TOXIC_ORB, TWISTED_SPOON, 
    ULTRA_BALL, UP_GRADE, WATER_STONE, WHITE_HERB, WIDE_LENS, WISE_GLASSES, 
    X_ACCURACY, X_ATTACK, X_DEFENSE, X_SP_ATK, X_SP_DEF, X_SPEED, ZINC, 
    ZOOM_LENS
}
